spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v-admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  # i18n
  messages:
    basename: i18n/messages

mybatis:
  mapper-locations: classpath:/mapper/vadmin/*Mapper.xml
  type-aliases-package: com.eraop.vadmin.entity

shiro:
  # rememberMe cookie有效时长，默认86400秒，即一天
  cookie-timeout: 86400
  # 免认证的路径配置，如静态资源，注册页面，验证码请求等
  anon-url:
    - /register
    - /js/*
    - /css/*
    - /fonts/*
    - /images/*
    - /swagger-ui.html
    - /v2/api-docs
    - /swagger-resources/**
    - /webjars/**
  # 登录 url
  login-url: /login
  # 登录成功后跳转的 url
  success-url: /index
  # 登出 url
  logout-url: /logout
  # 未授权跳转 url
  unauthorizedUrl: /403